version: '3'
services:
  couchdb:
    image: 'couchdb:latest'
    ports:
      - '5984:5984'
    environment: 
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: 'password'
      COUCHDB_SECRET: 'asdnuh3ynek3813u12h2n'